name: Build MineCPP

on:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libglu1-mesa-dev libglfw3-dev zlib1g-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install glfw mesa-glu zlib

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cd build && make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MineCPP-${{ matrix.os }}
          path: build/**
